#! /bin/bash
# Author: i0gan
# This script for starting lgx server

cd bin
if (($# < 1)); then
	sudo ./lgx -r
	exit
fi
	
if [ $1 == "-b" ]; then
	sudo ./lgx -r &
elif [ $1 == "-s" ]; then
	sudo ./lgx -s
else
	sudo ./lgx $1
fi
