#! /usr/bin/python
import socket
import _thread

sk = socket.socket(socket.AF_INET,socket.SOCK_STREAM)
sk.connect(('127.0.0.1', 80))

def recv_thread():
    print('recving...\n')
    while True:
        s = sk.recv(1024);
        print_recv(s)

def post(d):
    p =  b'POST / HTTP/1.1\r\n'
    p += b'Content-Length: ' + str(len(d)).encode() + b'\r\n'
    p += b'Connection: Keep-Alive\r\n'
    p += b'\r\n'
    p += d
    sk.send(p)

def print_recv(s):
    if(len(s) <= 10):
        return
    s = s.decode()
    sa = s.split('\r\n\r\n')
    header = sa[0]
    body = sa[1]
    print(body)
    
_thread.start_new_thread(recv_thread, ())

while True:
    s_msg = input()
    post(s_msg.encode())
